version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: cloudops-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
      MYSQL_DATABASE: inventory_db
      MYSQL_USER: cloudops_user
      MYSQL_PASSWORD: cloudops_pass123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data: